blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/stateful-y/python-package-copier/discussions
    about: Please use GitHub Discussions for questions and general discussions
  - name: Documentation
    url: https://python-package-copier.readthedocs.io/
    about: Check the documentation for guides and references
